# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44da664c9aaf741edb367724c581baf59b32d077fb69d2cb8d32dcb7367ffe8324f01bc0400e4fce1031c18e96f9aeece36e240b1fb9596540b2d20cae2d6d04

test:
  secret_key_base: 0099af756fe453770ec0a5561daebde4e871e71d747e276cdf8ae779d04da9bc130d65c02b09649cfd98bbeb8a7440e4d2bb93de0a71f1d1226f7a8e45174568

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
